aluno/urls.py
from django.urls import path
from aluno import views
from django.contrib.admin.views.decorators import staff_member_required
app_name = 'aluno'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('index/', views.index, name='dashboard'),
    path('search/', views.search, name='search'),

    path('alunos/', views.about, name='about-us'),

    path('<int:aluno_id>/', views.aluno, name='aluno'),


    # aluno CRUD
    path('aluno/<int:aluno_id>/detail',
         staff_member_required(views.aluno), name='aluno'),
    path('aluno/create/', staff_member_required(views.create), name='create'),
    path('aluno/<int:aluno_id>/update',
         staff_member_required(views.update), name='update'),
    path('aluno/<int:aluno_id>/delete',
         staff_member_required(views.delete), name='delete'),


    # user
    path('user/create/', views.register, name='register'),


    # login
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update', views.user_update, name='user_update'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('aluno.urls')),
    path('index/', include('aluno.urls')),
    path('about-us/', include('aluno.urls')),
    path('admin/', admin.site.urls),
]

aluno/models.py
from django.db import models

# Create your models here.


# campos para serem criados


# Tabela aluno ( model aluno)

# Nome completo - string
# Localidade - String
# Estado civil - string
# data nascimento - date
# data bastismo - date
# inicio das aulas  - date
# telefone
# operadora


# Tabela de endereços
# CEP - int
# Endereço - string
# n - int
# Bairro - string


# Tabela categoria

class Instrumento(models.Model):
    class Meta:
        verbose_name = 'Instrumento'
        verbose_name_plural = 'Instrumentos'

    nome = models.CharField(max_length=300)

    def __str__(self) -> str:
        return self.nome


class Localidade(models.Model):
    class Meta:
        verbose_name = 'Localidade'
        verbose_name_plural = 'Localidades'

    localidade = models.CharField(max_length=300)

    def __str__(self) -> str:
        return self.localidade


class Aluno(models.Model):
    nome_completo = models.CharField(max_length=200)
    localidade = models.ForeignKey(Localidade, on_delete=models.DO_NOTHING)
    estado_civil = models.CharField(max_length=100)
    telefone = models.CharField(max_length=200)
    operadora = models.CharField(max_length=20)
    date_nascimento = models.DateField()
    data_batismo = models.DateField(blank=True, null=True)
    inicio_gem = models.DateField()
    instrumento = models.ForeignKey(Instrumento,
                                    on_delete=models.DO_NOTHING,
                                    )

    def __str__(self) -> str:
        return f'{self.nome_completo}'

aluno/forms.py
from django.core.exceptions import ValidationError
from aluno.models import Aluno
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation


class AlunoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Aluno
        fields = (
            'nome_completo',
            'localidade',
            'instrumento',
            'estado_civil',
            'telefone',
            'operadora',
            'date_nascimento',
            'data_batismo',
            'inicio_gem',
        )

        widgets = {
            'date_nascimento': forms.TextInput(attrs={'type': 'date'}),
            'data_batismo': forms.TextInput(attrs={'type': 'date'}),
            'inicio_gem': forms.TextInput(attrs={'type': 'date'}),
        }

    def clean(self):

        return super().clean()


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        label='Primeiro Nome',
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        label='Segundo nome',
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Repita a senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1


class RegisterUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

aluno/views.py
from django.shortcuts import render
from aluno.models import Aluno


def index(request):
    alunos = Aluno.objects \
        .filter(show=True)\
        .order_by('-id')

    context = {
        'alunos': alunos,
    }

    return render(
        request,
        'aluno/index.html',
        context
    )


def about(request):

    alunos = Aluno.objects

    context = {
        'alunos': alunos
    }

    return render(
        request,
        'aluno/about-us.html',
        context

    )
# Create your views here.

aluno/views/aluno_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from aluno.forms import AlunoForm
from django.urls import reverse
from aluno.models import Aluno
from django.contrib.auth.decorators import login_required


@login_required(login_url='aluno:login')
def create(request):

    form_action = reverse('aluno:create')

    if request.method == 'POST':
        form = AlunoForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            aluno = form.save()
            return redirect('aluno:update', aluno_id=aluno.pk)

        return render(request,
                      'aluno/create.html',
                      context)

    context = {
        'form': AlunoForm(),
        'form_action': form_action
    }

    return render(request,
                  'aluno/create.html',
                  context
                  )


@login_required(login_url='aluno:login')
def update(request, aluno_id):
    aluno = get_object_or_404(Aluno, pk=aluno_id)
    form_action = reverse('aluno:update', args=(aluno_id,))
    if request.method == 'POST':
        form = AlunoForm(request.POST, instance=aluno)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            aluno = form.save()
            return redirect('aluno:update', aluno_id=aluno.pk)

        return render(request,
                      'aluno/create.html',
                      context)

    context = {
        'form': AlunoForm(instance=aluno),
        'form_action': form_action
    }

    return render(request,
                  'aluno/create.html',
                  context
                  )


@login_required(login_url='aluno:login')
def delete(request, aluno_id):
    aluno = get_object_or_404(Aluno, pk=aluno_id)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        aluno.delete()
        return redirect('aluno:index')

    return render(
        request,
        'aluno/aluno.html',
        {
            'aluno': aluno,
            'confirmation': confirmation,
        }
    )

aluno/views/aluno_views.py
from django.shortcuts import render, get_object_or_404, redirect
from aluno.models import Aluno
from django.db.models import Q
from django.core.paginator import Paginator
from django.db.models import Count
from django.contrib.auth.decorators import login_required


# -------------------------------------------------
import json


@login_required(login_url='aluno:login')
def index(request):

    alunos_por_instrumento = Aluno.objects.values(
        'instrumento__nome').annotate(quantidade_alunos=Count('id'))

    alunos_por_localidade = Aluno.objects.values(
        'localidade__localidade').annotate(quantidades=Count('id')

                                           )
    serialized_data = [
        {
            'label': resultado['instrumento__nome'],
            'y': resultado['quantidade_alunos']
        }
        for resultado in alunos_por_instrumento
    ]

    serialized_data2 = [
        {
            'label': resultado['localidade__localidade'],
            'y': resultado['quantidades']
        }
        for resultado in alunos_por_localidade
    ]

    context = {
        'site_title': 'Alunos'
    }

    return render(request,
                  'aluno/site/index.html',
                  {'context': context,
                   "alunosPorInstrumento": json.dumps(serialized_data),
                   "alunosPorLocalidade": json.dumps(serialized_data2)
                   })


@login_required(login_url='aluno:login')
def about(request):
    alunos = Aluno.objects.all() \
        .order_by('-id')

    paginator = Paginator(alunos, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Alunos'
    }
    return render(
        request,
        'aluno/site/about-us.html',
        context

    )


@login_required(login_url='aluno:login')
def search(request):
    search_value = request.GET.get('q').strip()

    if search_value == '':
        return redirect('aluno:about-us')

    alunos = Aluno.objects.all() \
        .filter(
        Q(nome_completo__icontains=search_value) |
        Q(instrumento__nome__icontains=search_value) |
        Q(localidade__icontains=search_value)
    )\
        .order_by('-id')

    paginator = Paginator(alunos, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Alunos'
    }
    return render(
        request,
        'aluno/site/about-us.html',
        context

    )


@login_required(login_url='aluno:login')
def aluno(request, aluno_id):

    # single_aluno = Aluno.objects.filter(pk=aluno_id).last()
    single_aluno = get_object_or_404(Aluno, pk=aluno_id)

    context = {
        'aluno': single_aluno,
        'site_title': 'Aluno'
    }
    return render(
        request,
        'aluno/aluno.html',
        context

    )

aluno/views/user_forms.py
from django.shortcuts import render, redirect
from aluno.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


def register(request):
    form = RegisterForm

    messages.info(request, 'Um texto qualquer')
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario Registrado')
            return redirect('aluno:dashboard')

    return render(
        request,
        'aluno/register.html',
        {
            'form': form
        }
    )


@login_required(login_url='aluno:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'aluno/register.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'aluno/register.html',
            {
                'form': form
            }
        )

    form.save()

    return redirect('aluno:logout')


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('aluno:dashboard')
        messages.error(request, 'Login inválido')

    return render(
        request,
        'aluno/login.html',
        {
            'form': form
        }
    )


@login_required(login_url='aluno:login')
def logout_view(request):
    auth.logout(request)
    return redirect('aluno:login')

aluno/templates/aluno/site/about-us.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{site_title}} - GEM</title>
  <link rel="stylesheet" href="{% static 'global/css/alunos.css' %} ">

</head>
<header class="header">
  {% include 'global/partials/_header.html' %}
  {% include 'global/partials/_search.html' %}
</header>

<body>
  <main class="content">
    {% block content %}

    {% if page_obj %}
     <div class="responsive-table">
      <table class="alunos-table">
        <caption class="table-caption">
          Alunos
        </caption>
        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">Nome</th>
            <th class="table-header">Localidade</th>
            <th class="table-header">Instrumento</th>
          </tr>
        </thead>
        <tbody>
          {% for aluno in page_obj %}
            <tr class="table-row">
              <td class="table-cel"> 
                <a href="{% url 'aluno:aluno' aluno.id %}" 
                  class="table-link">
                  {{aluno.id}}
                </a>
              </td>
              <td class="table-cel"> 
                {{aluno.nome_completo}}
              </td>
              <td class="table-cel"> 
                {{aluno.localidade}}
              </td>
              <td class="table-cel"> 
                {{aluno.instrumento}}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
     </div>
    {% include 'global/partials/_pagination.html' %}

     {% else %}
     <div class="single-aluno">
      <h1>Aluno não encontrado</h1>
  
   </div>

     {% endif %}
     {% endblock content %}
    

   
    </main>
</body>
</html>

aluno/templates/aluno/site/index.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'global/css/alunos.css' %}">
    <script>
        window.onload = function () {
         

            var alunosPorInstrumento = new CanvasJS.Chart("chartContainer", {
                exportEnabled: true,
                theme: "light2", // "light2", "dark1", "dark2"
                animationEnabled: true, // change to true
                 borderColor: "black",
                    borderThickness: 2,
                title:{
                    text: "Total de alunos por instrumento"
                },
                data: [
                {
                    // Change type to "bar", "area", "spline", "pie",etc.
                    type: "column",
                    indexLabel: "{y}",
                    dataPoints: {{ alunosPorInstrumento | safe }}
                }
                ]
            });
            alunosPorInstrumento.render();


            var chart2 = new CanvasJS.Chart("chartContainer2", {
                exportEnabled: true,
                theme: "light2", // "light2", "dark1", "dark2"
                animationEnabled: true, // change to true		
                title:{
                    text: "Alunos por localidade"
                },
                data: [
                {
                    // Change type to "bar", "area", "spline", "pie",etc.
                    type: "column",
                    indexLabel: "{y}",
                    dataPoints: {{ alunosPorLocalidade | safe }}
                }
                ]
            });

            chart2.render();
           
        
        }
    </script>
  <title>Alunos - GEM</title>

</head>
<body>
    <header class="header">
        {% include 'global/partials/_header.html' %}
    </header>
    <main class="content">
        <div id="chartContainer" style="width: 100%; height: 360px; border: 2px solid black"></div>
        <br>
        <div id="chartContainer2" style="width: 100%; height: 360px; border: 2px solid black"></div>
        <br>
   
        <script src="{% static 'global/js/canvasjs.min.js' %}"></script>
    </main>
</body>
</html>